agent: "MATD3"
env_name: "MultiWalker"
env_id: "multiwalker_v9"
env_seed: 1
continuous_action: True
learner: "MATD3_Learner"
policy: "MATD3_Policy"
representation: "Basic_Identical"
vectorize: "SubprocVecMultiAgentEnv"
runner: "MARL"

# more
benchmark: True
render: False
distributed_training: False
dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorflow"

# logging
logger: "wandb"  # Choices: "tensorboard", "wandb".
wandb_user_name: "yuzh2001-iscas"
project_name: "XuanCe_Benchmark"

render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
fps: 50  # The frames per second for the rendering videos in log file.
test_mode: False  # Whether to run in test mode.
device: "cuda:0"  # Choose an calculating device. PyTorch: "cpu", "cuda:0"; TensorFlow: "cpu"/"CPU", "gpu"/"GPU"; MindSpore: "CPU", "GPU", "Ascend", "Davinci".
master_port: '12355'  # The master port for current experiment when use distributed training.

# environment settings
n_walkers: 3  # walker数量
position_noise: 1e-3  # 位置观测噪声
angle_noise: 1e-3  # 角度观测噪声
forward_reward: 1.0  # 前进奖励系数
terminate_reward: -100.0  # 终止惩罚
fall_reward: -10.0  # 跌倒惩罚
shared_reward: True  # 是否共享奖励
terminate_on_fall: True  # 是否在跌倒时终止
remove_on_fall: False  # 是否在跌倒时移除walker
terrain_length: 200  # 地形长度
max_cycles: 500  # 最大步数

# network architecture
representation_hidden_size: []  # the units for each hidden layer
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: 'leaky_relu'
activation_action: 'sigmoid'
use_parameter_sharing: True
use_actions_mask: False


# training parameters
seed: 1  # 随机种子
parallels: 200  # 并行环境数量
buffer_size: 100000  # 增大buffer size以存储更多经验
batch_size: 512
learning_rate_actor: 0.001  # learning rate for actor
learning_rate_critic: 0.001  # learning rate for critic
gamma: 0.95  # discount factor
tau: 0.01  # soft update for target networks
actor_update_delay: 2

start_noise: 1.0
end_noise: 0.01
sigma: 0.1  # random noise for continuous actions
start_training: 1000  # start training after n episodes
running_steps: 100000000
training_frequency: 25

use_grad_clip: True
grad_clip_norm: 0.5

# training and evaluation
eval_interval: 100000  # 评估间隔
test_episode: 5  # 测试轮数

# logging
log_dir: "./logs/matd3/"  # 日志保存路径
model_dir: "./models/matd3/"  # 模型保存路径