defaults:
  - _self_

env_name: "MultiWalker"
env_id: "multiwalker_v9"
env_seed: 1
continuous_action: True

n_walkers: 3  # walker数量
position_noise: 1e-3  # 位置观测噪声
angle_noise: 1e-3  # 角度观测噪声
forward_reward: 1.0  # 前进奖励系数
terminate_reward: -100.0  # 终止惩罚
fall_reward: -10.0  # 跌倒惩罚
shared_reward: True  # 是否共享奖励
terminate_on_fall: True  # 是否在跌倒时终止
remove_on_fall: False  # 是否在跌倒时移除walker
terrain_length: 200  # 地形长度
max_cycles: 500  # 最大步数